/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.16
 * Generated at: 2025-11-20 21:51:30 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class dashboard_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(4);
    _jspx_dependants.put("jar:file:/C:/Users/el_ch/.m2/repository/org/glassfish/web/jakarta.servlet.jsp.jstl/3.0.1/jakarta.servlet.jsp.jstl-3.0.1.jar!/META-INF/c-1_2.tld", Long.valueOf(1664446278000L));
    _jspx_dependants.put("/WEB-INF/views/includes/footer.jsp", Long.valueOf(1763675376776L));
    _jspx_dependants.put("file:/C:/Users/el_ch/.m2/repository/org/glassfish/web/jakarta.servlet.jsp.jstl/3.0.1/jakarta.servlet.jsp.jstl-3.0.1.jar", Long.valueOf(1762018565336L));
    _jspx_dependants.put("/WEB-INF/views/includes/header.jsp", Long.valueOf(1763675179948L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fchoose;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fotherwise;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fchoose = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fotherwise = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fchoose.release();
    _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.release();
    _005fjspx_005ftagPool_005fc_005fotherwise.release();
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.release();
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"fr\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <title>Machine Monitor</title>\r\n");
      out.write("    <style>\r\n");
      out.write("        :root {\r\n");
      out.write("            --primary: #4361ee;\r\n");
      out.write("            --secondary: #3a0ca3;\r\n");
      out.write("            --gradient: linear-gradient(135deg, #4361ee, #3a0ca3);\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        * {\r\n");
      out.write("            margin: 0;\r\n");
      out.write("            padding: 0;\r\n");
      out.write("            box-sizing: border-box;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        body {\r\n");
      out.write("            font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;\r\n");
      out.write("            background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);\r\n");
      out.write("            min-height: 100vh;\r\n");
      out.write("            color: #2b2d42;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        /* Navigation SIMPLIFIÉE */\r\n");
      out.write("        .navbar {\r\n");
      out.write("            background: rgba(255, 255, 255, 0.98);\r\n");
      out.write("            padding: 1rem 2rem;\r\n");
      out.write("            display: flex;\r\n");
      out.write("            justify-content: space-between;\r\n");
      out.write("            align-items: center;\r\n");
      out.write("            box-shadow: 0 4px 6px -1px rgba(0, 0, 0, 0.1);\r\n");
      out.write("            border-bottom: 3px solid var(--primary);\r\n");
      out.write("            flex-wrap: wrap;\r\n");
      out.write("            gap: 1rem;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .nav-brand h1 {\r\n");
      out.write("            background: var(--gradient);\r\n");
      out.write("            -webkit-background-clip: text;\r\n");
      out.write("            -webkit-text-fill-color: transparent;\r\n");
      out.write("            background-clip: text;\r\n");
      out.write("            font-size: 1.8rem;\r\n");
      out.write("            font-weight: 700;\r\n");
      out.write("            white-space: nowrap;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .nav-links {\r\n");
      out.write("            display: flex;\r\n");
      out.write("            gap: 1rem;\r\n");
      out.write("            align-items: center;\r\n");
      out.write("            flex-wrap: wrap;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .nav-link {\r\n");
      out.write("            color: #2b2d42;\r\n");
      out.write("            text-decoration: none;\r\n");
      out.write("            padding: 0.6rem 1.2rem;\r\n");
      out.write("            border-radius: 25px;\r\n");
      out.write("            font-weight: 600;\r\n");
      out.write("            transition: all 0.3s ease;\r\n");
      out.write("            background: rgba(67, 97, 238, 0.1);\r\n");
      out.write("            white-space: nowrap;\r\n");
      out.write("            font-size: 0.9rem;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .nav-link:hover,\r\n");
      out.write("        .nav-link.active {\r\n");
      out.write("            background: var(--gradient);\r\n");
      out.write("            color: white;\r\n");
      out.write("            transform: translateY(-2px);\r\n");
      out.write("            box-shadow: 0 4px 15px rgba(67, 97, 238, 0.3);\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        /* Indicateur de status */\r\n");
      out.write("        .status-indicator {\r\n");
      out.write("            display: inline-flex;\r\n");
      out.write("            align-items: center;\r\n");
      out.write("            gap: 0.5rem;\r\n");
      out.write("            padding: 0.4rem 0.8rem;\r\n");
      out.write("            border-radius: 20px;\r\n");
      out.write("            font-size: 0.75rem;\r\n");
      out.write("            font-weight: 600;\r\n");
      out.write("            background: rgba(67, 97, 238, 0.1);\r\n");
      out.write("            color: var(--primary);\r\n");
      out.write("            white-space: nowrap;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .status-dot {\r\n");
      out.write("            width: 8px;\r\n");
      out.write("            height: 8px;\r\n");
      out.write("            border-radius: 50%;\r\n");
      out.write("            background: #06d6a0;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .status-down .status-dot {\r\n");
      out.write("            background: #ef476f;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        /* Responsive */\r\n");
      out.write("        @media (max-width: 768px) {\r\n");
      out.write("            .navbar {\r\n");
      out.write("                flex-direction: column;\r\n");
      out.write("                padding: 1rem;\r\n");
      out.write("                gap: 1rem;\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            .nav-links {\r\n");
      out.write("                justify-content: center;\r\n");
      out.write("                gap: 0.5rem;\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            .nav-link {\r\n");
      out.write("                padding: 0.5rem 1rem;\r\n");
      out.write("                font-size: 0.8rem;\r\n");
      out.write("            }\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .container {\r\n");
      out.write("            max-width: 1400px;\r\n");
      out.write("            margin: 2rem auto;\r\n");
      out.write("            padding: 0 2rem;\r\n");
      out.write("        }\r\n");
      out.write("    </style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("    <nav class=\"navbar\">\r\n");
      out.write("        <div class=\"nav-brand\">\r\n");
      out.write("            <h1>🚀 Machine Monitor</h1>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"nav-links\">\r\n");
      out.write("            <a href=\"/dashboard\" class=\"nav-link\">📊 Dashboard</a>\r\n");
      out.write("            <a href=\"/caisses\" class=\"nav-link\">🏦 Caisses</a>\r\n");
      out.write("            <a href=\"/tests\" class=\"nav-link\">🧪 Tests</a>\r\n");
      out.write("            <a href=\"/rapports\" class=\"nav-link\">📈 Rapports</a>\r\n");
      out.write("            <a href=\"/monitoring/metrics-dashboard\" class=\"nav-link\">📊 Monitoring</a>\r\n");
      out.write("\r\n");
      out.write("            <div class=\"status-indicator\" id=\"statusIndicator\">\r\n");
      out.write("                <div class=\"status-dot\"></div>\r\n");
      out.write("                <span id=\"statusText\">System OK</span>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </nav>\r\n");
      out.write("\r\n");
      out.write("    <main class=\"container\">");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div class=\"dashboard\">\r\n");
      out.write("   <!-- En-tête -->\r\n");
      out.write("   <div class=\"page-header\">\r\n");
      out.write("      <h2>📊 Tableau de Bord Monitor</h2>\r\n");
      out.write("      <div class=\"header-actions\">\r\n");
      out.write("         <span class=\"update-badge\">🟢 Système opérationnel</span>\r\n");
      out.write("      </div>\r\n");
      out.write("   </div>\r\n");
      out.write("\r\n");
      out.write("   <!-- Indicateur de statut -->\r\n");
      out.write("   <div style=\"background: linear-gradient(135deg, #4cc9f0, #4361ee); color: white; padding: 1rem; border-radius: 10px; margin-bottom: 1rem;\">\r\n");
      out.write("      <div style=\"display: flex; justify-content: space-between; align-items: center;\">\r\n");
      out.write("         <div>\r\n");
      out.write("            <strong>📊 Vue d'ensemble</strong>\r\n");
      out.write("            <div style=\"font-size: 0.9rem; opacity: 0.9;\">\r\n");
      out.write("               ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${totalCaisses}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(" caisses • ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${totalTests}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(" tests\r\n");
      out.write("            </div>\r\n");
      out.write("         </div>\r\n");
      out.write("         <div style=\"font-size: 0.8rem; background: rgba(255,255,255,0.2); padding: 0.25rem 0.75rem; border-radius: 15px;\">\r\n");
      out.write("            🟢 Système opérationnel\r\n");
      out.write("         </div>\r\n");
      out.write("      </div>\r\n");
      out.write("   </div>\r\n");
      out.write("\r\n");
      out.write("   <!-- NOUVEAU : Section Actions Rapides - Version Améliorée -->\r\n");
      out.write("   <div style=\"background: rgba(255, 255, 255, 0.1); padding: 1.5rem; border-radius: 15px; margin-bottom: 2rem; border: 1px solid rgba(255, 255, 255, 0.2);\">\r\n");
      out.write("      <h3 style=\"color: white; margin-bottom: 1.5rem; text-align: center;\">🚀 Actions Rapides</h3>\r\n");
      out.write("      \r\n");
      out.write("      <div style=\"display: grid; grid-template-columns: repeat(auto-fit, minmax(300px, 1fr)); gap: 1rem; align-items: start;\">\r\n");
      out.write("         \r\n");
      out.write("         <!-- Lancer Tous les Tests -->\r\n");
      out.write("         <div style=\"display: flex; flex-direction: column; gap: 0.5rem;\">\r\n");
      out.write("            <form action=\"/tests/lancer-tous\" method=\"post\" style=\"margin: 0;\">\r\n");
      out.write("               <button type=\"button\" onclick=\"lancerTousTests()\" \r\n");
      out.write("                       style=\"display: flex; align-items: center; gap: 0.75rem; padding: 1rem 1.5rem; background: linear-gradient(135deg, #06d6a0, #118ab2); color: white; border: none; border-radius: 12px; font-weight: 600; cursor: pointer; transition: all 0.3s ease; width: 100%; justify-content: center;\"\r\n");
      out.write("                       onmouseover=\"this.style.transform='translateY(-2px)'; this.style.boxShadow='0 8px 25px rgba(0,0,0,0.2)';\"\r\n");
      out.write("                       onmouseout=\"this.style.transform='translateY(0)'; this.style.boxShadow='none';\">\r\n");
      out.write("                  <span style=\"font-size: 1.2rem;\">🎯</span>\r\n");
      out.write("                  <span>Lancer Tous les Tests</span>\r\n");
      out.write("               </button>\r\n");
      out.write("            </form>\r\n");
      out.write("            <div style=\"font-size: 0.8rem; color: rgba(255,255,255,0.8); text-align: center;\">\r\n");
      out.write("               Exécute tous les tests actifs\r\n");
      out.write("            </div>\r\n");
      out.write("         </div>\r\n");
      out.write("\r\n");
      out.write("         <!-- Tests par Catégorie -->\r\n");
      out.write("         <div style=\"display: flex; flex-direction: column; gap: 0.5rem;\">\r\n");
      out.write("            <form action=\"/tests/lancer-categorie\" method=\"post\" style=\"margin: 0; display: flex; flex-direction: column; gap: 0.75rem;\">\r\n");
      out.write("               <select name=\"categorie\" required \r\n");
      out.write("                       style=\"padding: 0.75rem; border: 1px solid #ddd; border-radius: 8px; background: white; width: 100%; font-size: 0.9rem;\">\r\n");
      out.write("                  <option value=\"\">Choisir une catégorie</option>\r\n");
      out.write("                  <option value=\"conformite\">Conformité</option>\r\n");
      out.write("                  <option value=\"processus_metier\">Processus Métier</option>\r\n");
      out.write("                  <option value=\"surveillance\">Surveillance</option>\r\n");
      out.write("                  <option value=\"ged\">GED</option>\r\n");
      out.write("                  <option value=\"integration\">Intégration</option>\r\n");
      out.write("                  <option value=\"web\">Applications Web</option>\r\n");
      out.write("               </select>\r\n");
      out.write("               <button type=\"button\" onclick=\"lancerTestsCategorie(this.previousElementSibling.value)\" \r\n");
      out.write("                       style=\"display: flex; align-items: center; gap: 0.75rem; padding: 1rem 1.5rem; background: linear-gradient(135deg, #7209b7, #3a0ca3); color: white; border: none; border-radius: 12px; font-weight: 600; cursor: pointer; transition: all 0.3s ease; width: 100%; justify-content: center;\"\r\n");
      out.write("                       onmouseover=\"this.style.transform='translateY(-2px)'; this.style.boxShadow='0 8px 25px rgba(0,0,0,0.2)';\"\r\n");
      out.write("                       onmouseout=\"this.style.transform='translateY(0)'; this.style.boxShadow='none';\">\r\n");
      out.write("                  <span style=\"font-size: 1.2rem;\">📁</span>\r\n");
      out.write("                  <span>Tests par Catégorie</span>\r\n");
      out.write("               </button>\r\n");
      out.write("            </form>\r\n");
      out.write("            <div style=\"font-size: 0.8rem; color: rgba(255,255,255,0.8); text-align: center;\">\r\n");
      out.write("               Tests ciblés par catégorie\r\n");
      out.write("            </div>\r\n");
      out.write("         </div>\r\n");
      out.write("\r\n");
      out.write("         <!-- Voir les Rapports -->\r\n");
      out.write("         <div style=\"display: flex; flex-direction: column; gap: 0.5rem;\">\r\n");
      out.write("            <a href=\"/rapports\" \r\n");
      out.write("               style=\"display: flex; align-items: center; gap: 0.75rem; padding: 1rem 1.5rem; background: linear-gradient(135deg, #ff9e00, #ff6b6b); color: white; text-decoration: none; border-radius: 12px; font-weight: 600; transition: all 0.3s ease; width: 100%; justify-content: center;\"\r\n");
      out.write("               onmouseover=\"this.style.transform='translateY(-2px)'; this.style.boxShadow='0 8px 25px rgba(0,0,0,0.2)';\"\r\n");
      out.write("               onmouseout=\"this.style.transform='translateY(0)'; this.style.boxShadow='none';\">\r\n");
      out.write("               <span style=\"font-size: 1.2rem;\">📈</span>\r\n");
      out.write("               <span>Voir les Rapports</span>\r\n");
      out.write("            </a>\r\n");
      out.write("            <div style=\"font-size: 0.8rem; color: rgba(255,255,255,0.8); text-align: center;\">\r\n");
      out.write("               Statistiques et analyses\r\n");
      out.write("            </div>\r\n");
      out.write("         </div>\r\n");
      out.write("\r\n");
      out.write("      </div>\r\n");
      out.write("\r\n");
      out.write("      <!-- Indicateur Temps Réel -->\r\n");
      out.write("      <div style=\"text-align: center; margin-top: 1rem; padding-top: 1rem; border-top: 1px solid rgba(255,255,255,0.2);\">\r\n");
      out.write("         <div style=\"display: inline-flex; align-items: center; gap: 0.5rem; background: rgba(255,255,255,0.2); color: white; padding: 0.5rem 1rem; border-radius: 20px; font-size: 0.9rem;\">\r\n");
      out.write("            <span>🔄</span>\r\n");
      out.write("            <span>Données temps réel</span>\r\n");
      out.write("            <span style=\"font-weight: bold;\">•</span>\r\n");
      out.write("            <span>MAJ: ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${derniereMaj}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</span>\r\n");
      out.write("         </div>\r\n");
      out.write("      </div>\r\n");
      out.write("   </div>\r\n");
      out.write("\r\n");
      out.write("   <!-- Cartes de statistiques -->\r\n");
      out.write("   <div style=\"display: grid; grid-template-columns: repeat(auto-fit, minmax(250px, 1fr)); gap: 1.5rem; margin-bottom: 2rem;\">\r\n");
      out.write("      <div style=\"background: white; padding: 2rem; border-radius: 15px; text-align: center; box-shadow: 0 4px 6px rgba(0,0,0,0.1);\">\r\n");
      out.write("         <div style=\"font-size: 2.5rem; margin-bottom: 0.5rem;\">🏦</div>\r\n");
      out.write("         <div style=\"font-size: 3rem; font-weight: bold; color: #4361ee; margin-bottom: 0.5rem;\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${totalCaisses}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</div>\r\n");
      out.write("         <div style=\"font-size: 1.2rem; font-weight: 600; color: #495057; margin-bottom: 0.25rem;\">Total Caisses</div>\r\n");
      out.write("         <div style=\"font-size: 0.9rem; color: #6c757d;\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${activeCaisses}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(" actives</div>\r\n");
      out.write("      </div>\r\n");
      out.write("      \r\n");
      out.write("      <div style=\"background: white; padding: 2rem; border-radius: 15px; text-align: center; box-shadow: 0 4px 6px rgba(0,0,0,0.1);\">\r\n");
      out.write("         <div style=\"font-size: 2.5rem; margin-bottom: 0.5rem;\">🧪</div>\r\n");
      out.write("         <div style=\"font-size: 3rem; font-weight: bold; color: #4361ee; margin-bottom: 0.5rem;\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${totalTests}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</div>\r\n");
      out.write("         <div style=\"font-size: 1.2rem; font-weight: 600; color: #495057; margin-bottom: 0.25rem;\">Total Tests</div>\r\n");
      out.write("         <div style=\"font-size: 0.9rem; color: #6c757d;\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${activeTests}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(" actifs</div>\r\n");
      out.write("      </div>\r\n");
      out.write("      \r\n");
      out.write("      <div style=\"background: linear-gradient(135deg, #06d6a0, #118ab2); color: white; padding: 2rem; border-radius: 15px; text-align: center; box-shadow: 0 4px 6px rgba(0,0,0,0.1);\">\r\n");
      out.write("         <div style=\"font-size: 2.5rem; margin-bottom: 0.5rem;\">✅</div>\r\n");
      out.write("         <div style=\"font-size: 3rem; font-weight: bold; margin-bottom: 0.5rem;\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${testsReussis}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</div>\r\n");
      out.write("         <div style=\"font-size: 1.2rem; font-weight: 600; margin-bottom: 0.25rem;\">Tests Réussis</div>\r\n");
      out.write("         <div style=\"font-size: 0.9rem; opacity: 0.9;\">Aujourd'hui</div>\r\n");
      out.write("      </div>\r\n");
      out.write("      \r\n");
      out.write("      <div style=\"background: linear-gradient(135deg, #ef476f, #ff6b6b); color: white; padding: 2rem; border-radius: 15px; text-align: center; box-shadow: 0 4px 6px rgba(0,0,0,0.1);\">\r\n");
      out.write("         <div style=\"font-size: 2.5rem; margin-bottom: 0.5rem;\">❌</div>\r\n");
      out.write("         <div style=\"font-size: 3rem; font-weight: bold; margin-bottom: 0.5rem;\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${testsEchoues}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</div>\r\n");
      out.write("         <div style=\"font-size: 1.2rem; font-weight: 600; margin-bottom: 0.25rem;\">Tests Échoués</div>\r\n");
      out.write("         <div style=\"font-size: 0.9rem; opacity: 0.9;\">Aujourd'hui</div>\r\n");
      out.write("      </div>\r\n");
      out.write("   </div>\r\n");
      out.write("\r\n");
      out.write("   <!-- Navigation rapide -->\r\n");
      out.write("   <div style=\"display: grid; grid-template-columns: repeat(auto-fit, minmax(250px, 1fr)); gap: 1rem; margin-bottom: 2rem;\">\r\n");
      out.write("      <a href=\"/caisses\" style=\"display: flex; align-items: center; gap: 0.75rem; padding: 1.5rem; color: white; text-decoration: none; border-radius: 12px; transition: all 0.3s ease; background: linear-gradient(135deg, #4361ee, #3a0ca3);\">\r\n");
      out.write("         <span style=\"font-size: 1.5rem;\">🏦</span>\r\n");
      out.write("         <span style=\"flex: 1; font-weight: 600; font-size: 1.1rem;\">Gérer les Caisses</span>\r\n");
      out.write("         <span style=\"background: rgba(255,255,255,0.2); padding: 0.5rem 1rem; border-radius: 20px; font-weight: bold; font-size: 0.9rem;\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${totalCaisses}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</span>\r\n");
      out.write("      </a>\r\n");
      out.write("      \r\n");
      out.write("      <a href=\"/tests\" style=\"display: flex; align-items: center; gap: 0.75rem; padding: 1.5rem; color: white; text-decoration: none; border-radius: 12px; transition: all 0.3s ease; background: linear-gradient(135deg, #7209b7, #560bad);\">\r\n");
      out.write("         <span style=\"font-size: 1.5rem;\">🧪</span>\r\n");
      out.write("         <span style=\"flex: 1; font-weight: 600; font-size: 1.1rem;\">Gérer les Tests</span>\r\n");
      out.write("         <span style=\"background: rgba(255,255,255,0.2); padding: 0.5rem 1rem; border-radius: 20px; font-weight: bold; font-size: 0.9rem;\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${totalTests}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</span>\r\n");
      out.write("      </a>\r\n");
      out.write("      \r\n");
      out.write("      <a href=\"/caisses/creer\" style=\"display: flex; align-items: center; gap: 0.75rem; padding: 1.5rem; color: white; text-decoration: none; border-radius: 12px; transition: all 0.3s ease; background: linear-gradient(135deg, #06d6a0, #118ab2);\">\r\n");
      out.write("         <span style=\"font-size: 1.5rem;\">➕</span>\r\n");
      out.write("         <span style=\"flex: 1; font-weight: 600; font-size: 1.1rem;\">Nouvelle Caisse</span>\r\n");
      out.write("      </a>\r\n");
      out.write("      \r\n");
      out.write("      <a href=\"/tests/creer\" style=\"display: flex; align-items: center; gap: 0.75rem; padding: 1.5rem; color: white; text-decoration: none; border-radius: 12px; transition: all 0.3s ease; background: linear-gradient(135deg, #06d6a0, #118ab2);\">\r\n");
      out.write("         <span style=\"font-size: 1.5rem;\">➕</span>\r\n");
      out.write("         <span style=\"flex: 1; font-weight: 600; font-size: 1.1rem;\">Nouveau Test</span>\r\n");
      out.write("      </a>\r\n");
      out.write("   </div>\r\n");
      out.write("\r\n");
      out.write("   <!-- Grille de contenu détaillé -->\r\n");
      out.write("   <div style=\"display: grid; grid-template-columns: 1fr 1fr; gap: 2rem;\">\r\n");
      out.write("      <!-- Caisses Actives -->\r\n");
      out.write("      <div style=\"background: white; border-radius: 15px; box-shadow: 0 4px 6px rgba(0,0,0,0.1); overflow: hidden;\">\r\n");
      out.write("         <div style=\"display: flex; justify-content: space-between; align-items: center; padding: 1.5rem; background: #f8f9fa; border-bottom: 1px solid #e9ecef;\">\r\n");
      out.write("            <h3 style=\"margin: 0; color: #4361ee; font-size: 1.3rem;\">🏦 Caisses Actives</h3>\r\n");
      out.write("            <span style=\"background: #4361ee; color: white; padding: 0.5rem 1rem; border-radius: 15px; font-size: 0.9rem; font-weight: 600;\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${activeCaisses}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write('/');
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${totalCaisses}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</span>\r\n");
      out.write("         </div>\r\n");
      out.write("         <div style=\"padding: 1rem; max-height: 400px; overflow-y: auto;\">\r\n");
      out.write("            ");
      if (_jspx_meth_c_005fchoose_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("         </div>\r\n");
      out.write("      </div>\r\n");
      out.write("      \r\n");
      out.write("      <!-- Tests Actifs -->\r\n");
      out.write("      <div style=\"background: white; border-radius: 15px; box-shadow: 0 4px 6px rgba(0,0,0,0.1); overflow: hidden;\">\r\n");
      out.write("         <div style=\"display: flex; justify-content: space-between; align-items: center; padding: 1.5rem; background: #f8f9fa; border-bottom: 1px solid #e9ecef;\">\r\n");
      out.write("            <h3 style=\"margin: 0; color: #4361ee; font-size: 1.3rem;\">🧪 Tests Actifs</h3>\r\n");
      out.write("            <span style=\"background: #4361ee; color: white; padding: 0.5rem 1rem; border-radius: 15px; font-size: 0.9rem; font-weight: 600;\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${activeTests}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write('/');
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${totalTests}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</span>\r\n");
      out.write("         </div>\r\n");
      out.write("         <div style=\"padding: 1rem; max-height: 400px; overflow-y: auto;\">\r\n");
      out.write("            ");
      if (_jspx_meth_c_005fchoose_005f1(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("         </div>\r\n");
      out.write("      </div>\r\n");
      out.write("   </div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<!-- 🎨 SCRIPT POUR LA POPUP COHÉRENTE -->\r\n");
      out.write("<script>\r\n");
      out.write("/**\r\n");
      out.write(" * 🎨 Popup de confirmation cohérente avec le style de l'application\r\n");
      out.write(" */\r\n");
      out.write("function confirmerLancementTests(description) {\r\n");
      out.write("    // Créer l'overlay\r\n");
      out.write("    const overlay = document.createElement('div');\r\n");
      out.write("    overlay.style.cssText = `\r\n");
      out.write("        position: fixed;\r\n");
      out.write("        top: 0;\r\n");
      out.write("        left: 0;\r\n");
      out.write("        width: 100%;\r\n");
      out.write("        height: 100%;\r\n");
      out.write("        background: rgba(0, 0, 0, 0.5);\r\n");
      out.write("        display: flex;\r\n");
      out.write("        justify-content: center;\r\n");
      out.write("        align-items: center;\r\n");
      out.write("        z-index: 10000;\r\n");
      out.write("        animation: fadeIn 0.3s ease;\r\n");
      out.write("    `;\r\n");
      out.write("\r\n");
      out.write("    // Créer la popup\r\n");
      out.write("    const popup = document.createElement('div');\r\n");
      out.write("    popup.style.cssText = `\r\n");
      out.write("        background: white;\r\n");
      out.write("        padding: 2rem;\r\n");
      out.write("        border-radius: 15px;\r\n");
      out.write("        box-shadow: 0 20px 60px rgba(0,0,0,0.3);\r\n");
      out.write("        text-align: center;\r\n");
      out.write("        max-width: 400px;\r\n");
      out.write("        width: 90%;\r\n");
      out.write("        animation: slideIn 0.3s ease;\r\n");
      out.write("        border: 1px solid #e9ecef;\r\n");
      out.write("    `;\r\n");
      out.write("\r\n");
      out.write("    // Contenu de la popup\r\n");
      out.write("    popup.innerHTML = `\r\n");
      out.write("        <div style=\"font-size: 3rem; margin-bottom: 1rem;\">🚀</div>\r\n");
      out.write("        <h3 style=\"color: #4361ee; margin-bottom: 1rem; font-size: 1.5rem;\">Confirmation de lancement</h3>\r\n");
      out.write("        <p style=\"color: #495057; margin-bottom: 2rem; line-height: 1.5;\">\r\n");
      out.write("            Êtes-vous sûr de vouloir lancer <strong>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${description}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</strong> ?\r\n");
      out.write("        </p>\r\n");
      out.write("        <div style=\"display: flex; gap: 1rem; justify-content: center;\">\r\n");
      out.write("            <button onclick=\"fermerPopup(false)\" \r\n");
      out.write("                    style=\"padding: 0.75rem 2rem; background: #6c757d; color: white; border: none; border-radius: 25px; font-weight: 600; cursor: pointer; transition: all 0.3s ease;\"\r\n");
      out.write("                    onmouseover=\"this.style.background='#5a6268'; this.style.transform='translateY(-2px)';\"\r\n");
      out.write("                    onmouseout=\"this.style.background='#6c757d'; this.style.transform='translateY(0)';\">\r\n");
      out.write("                Annuler\r\n");
      out.write("            </button>\r\n");
      out.write("            <button onclick=\"fermerPopup(true)\" \r\n");
      out.write("                    style=\"padding: 0.75rem 2rem; background: linear-gradient(135deg, #06d6a0, #118ab2); color: white; border: none; border-radius: 25px; font-weight: 600; cursor: pointer; transition: all 0.3s ease;\"\r\n");
      out.write("                    onmouseover=\"this.style.transform='translateY(-2px)'; this.style.boxShadow='0 8px 25px rgba(6, 214, 160, 0.3)';\"\r\n");
      out.write("                    onmouseout=\"this.style.transform='translateY(0)'; this.style.boxShadow='none';\">\r\n");
      out.write("                🚀 Lancer\r\n");
      out.write("            </button>\r\n");
      out.write("        </div>\r\n");
      out.write("    `;\r\n");
      out.write("\r\n");
      out.write("    // Variables pour gérer la réponse\r\n");
      out.write("    let resolveFunction;\r\n");
      out.write("    const promise = new Promise((resolve) => {\r\n");
      out.write("        resolveFunction = resolve;\r\n");
      out.write("    });\r\n");
      out.write("\r\n");
      out.write("    // Fonction pour fermer la popup\r\n");
      out.write("    window.fermerPopup = function(confirme) {\r\n");
      out.write("        document.body.removeChild(overlay);\r\n");
      out.write("        resolveFunction(confirme);\r\n");
      out.write("    };\r\n");
      out.write("\r\n");
      out.write("    // Ajouter à la page\r\n");
      out.write("    overlay.appendChild(popup);\r\n");
      out.write("    document.body.appendChild(overlay);\r\n");
      out.write("\r\n");
      out.write("    // Fermer en cliquant en dehors\r\n");
      out.write("    overlay.addEventListener('click', function(e) {\r\n");
      out.write("        if (e.target === overlay) {\r\n");
      out.write("            fermerPopup(false);\r\n");
      out.write("        }\r\n");
      out.write("    });\r\n");
      out.write("\r\n");
      out.write("    return promise;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/**\r\n");
      out.write(" * 🎯 Gestionnaire pour le lancement de tous les tests\r\n");
      out.write(" */\r\n");
      out.write("async function lancerTousTests() {\r\n");
      out.write("    const confirme = await confirmerLancementTests('tous les tests actifs');\r\n");
      out.write("    if (confirme) {\r\n");
      out.write("        // Soumettre le formulaire\r\n");
      out.write("        document.querySelector('form[action=\"/tests/lancer-tous\"]').submit();\r\n");
      out.write("    }\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/**\r\n");
      out.write(" * 🎯 Gestionnaire pour le lancement par catégorie\r\n");
      out.write(" */\r\n");
      out.write("async function lancerTestsCategorie(categorie) {\r\n");
      out.write("    if (!categorie) {\r\n");
      out.write("        alert('⚠️ Veuillez sélectionner une catégorie');\r\n");
      out.write("        return;\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("    const nomCategorie = getNomCategorie(categorie);\r\n");
      out.write("    const confirme = await confirmerLancementTests(`les tests de la catégorie ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${nomCategorie}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("`);\r\n");
      out.write("    if (confirme) {\r\n");
      out.write("        // Soumettre le formulaire\r\n");
      out.write("        const form = document.querySelector('form[action=\"/tests/lancer-categorie\"]');\r\n");
      out.write("        form.querySelector('select[name=\"categorie\"]').value = categorie;\r\n");
      out.write("        form.submit();\r\n");
      out.write("    }\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/**\r\n");
      out.write(" * 📋 Obtenir le nom lisible de la catégorie\r\n");
      out.write(" */\r\n");
      out.write("function getNomCategorie(codeCategorie) {\r\n");
      out.write("    const categories = {\r\n");
      out.write("        'conformite': 'Conformité',\r\n");
      out.write("        'processus_metier': 'Processus Métier', \r\n");
      out.write("        'surveillance': 'Surveillance',\r\n");
      out.write("        'ged': 'GED',\r\n");
      out.write("        'integration': 'Intégration',\r\n");
      out.write("        'web': 'Applications Web'\r\n");
      out.write("    };\r\n");
      out.write("    return categories[codeCategorie] || codeCategorie;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("// Animations CSS\r\n");
      out.write("const style = document.createElement('style');\r\n");
      out.write("style.textContent = `\r\n");
      out.write("    @keyframes fadeIn {\r\n");
      out.write("        from { opacity: 0; }\r\n");
      out.write("        to { opacity: 1; }\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("    @keyframes slideIn {\r\n");
      out.write("        from { \r\n");
      out.write("            opacity: 0;\r\n");
      out.write("            transform: translateY(-20px) scale(0.9);\r\n");
      out.write("        }\r\n");
      out.write("        to { \r\n");
      out.write("            opacity: 1;\r\n");
      out.write("            transform: translateY(0) scale(1);\r\n");
      out.write("        }\r\n");
      out.write("    }\r\n");
      out.write("`;\r\n");
      out.write("document.head.appendChild(style);\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write("/* Styles de base pour la cohérence */\r\n");
      out.write(".dashboard {\r\n");
      out.write("   max-width: 1400px;\r\n");
      out.write("   margin: 0 auto;\r\n");
      out.write("   padding: 20px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".page-header {\r\n");
      out.write("   display: flex;\r\n");
      out.write("   justify-content: space-between;\r\n");
      out.write("   align-items: center;\r\n");
      out.write("   margin-bottom: 2rem;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".update-badge {\r\n");
      out.write("   background: rgba(255, 255, 255, 0.2);\r\n");
      out.write("   color: white;\r\n");
      out.write("   padding: 0.5rem 1rem;\r\n");
      out.write("   border-radius: 20px;\r\n");
      out.write("   font-size: 0.9rem;\r\n");
      out.write("   font-weight: 600;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* Effets de hover */\r\n");
      out.write("a:hover {\r\n");
      out.write("   transform: translateY(-2px);\r\n");
      out.write("   box-shadow: 0 8px 25px rgba(0,0,0,0.2);\r\n");
      out.write("   text-decoration: none;\r\n");
      out.write("   color: white;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* Scrollbar personnalisée */\r\n");
      out.write("div[style*=\"overflow-y: auto\"]::-webkit-scrollbar {\r\n");
      out.write("   width: 6px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("div[style*=\"overflow-y: auto\"]::-webkit-scrollbar-track {\r\n");
      out.write("   background: #f1f1f1;\r\n");
      out.write("   border-radius: 3px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("div[style*=\"overflow-y: auto\"]::-webkit-scrollbar-thumb {\r\n");
      out.write("   background: #c1c1c1;\r\n");
      out.write("   border-radius: 3px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("div[style*=\"overflow-y: auto\"]::-webkit-scrollbar-thumb:hover {\r\n");
      out.write("   background: #a8a8a8;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* Responsive */\r\n");
      out.write("@media (max-width: 1024px) {\r\n");
      out.write("   .dashboard {\r\n");
      out.write("      padding: 10px;\r\n");
      out.write("   }\r\n");
      out.write("   \r\n");
      out.write("   div[style*=\"grid-template-columns: 1fr 1fr\"] {\r\n");
      out.write("      grid-template-columns: 1fr;\r\n");
      out.write("   }\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("@media (max-width: 768px) {\r\n");
      out.write("   .page-header {\r\n");
      out.write("      flex-direction: column;\r\n");
      out.write("      gap: 1rem;\r\n");
      out.write("      text-align: center;\r\n");
      out.write("   }\r\n");
      out.write("   \r\n");
      out.write("   div[style*=\"grid-template-columns: repeat(auto-fit, minmax(250px, 1fr))\"] {\r\n");
      out.write("      grid-template-columns: 1fr;\r\n");
      out.write("   }\r\n");
      out.write("   \r\n");
      out.write("   div[style*=\"grid-template-columns: repeat(auto-fit, minmax(300px, 1fr))\"] {\r\n");
      out.write("      grid-template-columns: 1fr;\r\n");
      out.write("   }\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("</main>\r\n");
      out.write("<footer style=\"\r\n");
      out.write("    background: linear-gradient(135deg, #2c3e50 0%, #34495e 100%);\r\n");
      out.write("    color: white;\r\n");
      out.write("    padding: 1rem 2rem;\r\n");
      out.write("    margin-top: 3rem;\r\n");
      out.write("    border-top: 3px solid #4361ee;\r\n");
      out.write("    font-family: 'Segoe UI', Arial, sans-serif;\r\n");
      out.write("\">\r\n");
      out.write("    <div style=\"max-width: 1400px; margin: 0 auto;\">\r\n");
      out.write("        <!-- Ligne principale -->\r\n");
      out.write("        <div style=\"display: flex; justify-content: space-between; align-items: center; flex-wrap: wrap; gap: 1rem;\">\r\n");
      out.write("            <!-- Section gauche -->\r\n");
      out.write("            <div style=\"text-align: left; flex: 1;\">\r\n");
      out.write("                <h3 style=\"color: #fff; margin: 0; font-size: 1.2rem; font-weight: 600;\">\r\n");
      out.write("                    Machine Monitor\r\n");
      out.write("                </h3>\r\n");
      out.write("                <p style=\"color: #bdc3c7; margin: 0.3rem 0 0 0; font-size: 0.9rem;\">\r\n");
      out.write("                    SystÃ¨me de surveillance des caisses et tests automatisÃ©s\r\n");
      out.write("                </p>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <!-- Section centrale -->\r\n");
      out.write("            <div style=\"text-align: center; flex: 1;\">\r\n");
      out.write("                <p style=\"color: #ecf0f1; margin: 0; font-size: 0.85rem; font-weight: 500;\">\r\n");
      out.write("                    Â© 2024 Machine Monitor - Tous droits rÃ©servÃ©s â¢ DÃ©veloppÃ© avec soin\r\n");
      out.write("                </p>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <!-- Section droite -->\r\n");
      out.write("            <div style=\"text-align: right; flex: 1;\">\r\n");
      out.write("                <div style=\"display: flex; gap: 1.5rem; justify-content: flex-end; margin-bottom: 0.5rem;\">\r\n");
      out.write("                    <span style=\"color: #ecf0f1; font-size: 0.9rem;\">ð Monitoring temps rÃ©el</span>\r\n");
      out.write("                    <span style=\"color: #ecf0f1; font-size: 0.9rem;\">â¡ Performances</span>\r\n");
      out.write("                    <span style=\"color: #ecf0f1; font-size: 0.9rem;\">ð SÃ©curitÃ©</span>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <!-- Ligne secondaire -->\r\n");
      out.write("        <div style=\"margin-top: 1rem; padding-top: 0.8rem; border-top: 1px solid #4a6572;\">\r\n");
      out.write("            <div style=\"display: flex; justify-content: space-between; align-items: center; flex-wrap: wrap; gap: 1rem;\">\r\n");
      out.write("                <div style=\"color: #95a5a6; font-size: 0.8rem;\">\r\n");
      out.write("                    ð¢ Gestion des partitions et CR â¢ ð§ª Tests de conformitÃ©\r\n");
      out.write("                </div>\r\n");
      out.write("                <div style=\"color: #95a5a6; font-size: 0.8rem;\">\r\n");
      out.write("                    ð Dashboard â¢ ð¦ Caisses â¢ ð§ª Tests â¢ ð Monitoring\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</footer>\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("    // VÃ©rification du status\r\n");
      out.write("    function checkHealthStatus() {\r\n");
      out.write("        fetch('/monitoring/health')\r\n");
      out.write("            .then(response => response.json())\r\n");
      out.write("            .then(data => {\r\n");
      out.write("                const statusIndicator = document.getElementById('statusIndicator');\r\n");
      out.write("                const statusText = document.getElementById('statusText');\r\n");
      out.write("\r\n");
      out.write("                if (data.status === 'UP') {\r\n");
      out.write("                    statusIndicator.classList.remove('status-down');\r\n");
      out.write("                    statusText.textContent = 'SystÃ¨me OK';\r\n");
      out.write("                } else {\r\n");
      out.write("                    statusIndicator.classList.add('status-down');\r\n");
      out.write("                    statusText.textContent = 'ProblÃ¨mes';\r\n");
      out.write("                }\r\n");
      out.write("            })\r\n");
      out.write("            .catch(error => {\r\n");
      out.write("                const statusIndicator = document.getElementById('statusIndicator');\r\n");
      out.write("                const statusText = document.getElementById('statusText');\r\n");
      out.write("                statusIndicator.classList.add('status-down');\r\n");
      out.write("                statusText.textContent = 'Erreur';\r\n");
      out.write("            });\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    document.addEventListener('DOMContentLoaded', function() {\r\n");
      out.write("        checkHealthStatus();\r\n");
      out.write("        setInterval(checkHealthStatus, 30000);\r\n");
      out.write("    });\r\n");
      out.write("</script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fchoose_005f0(jakarta.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    jakarta.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:choose
    org.apache.taglibs.standard.tag.common.core.ChooseTag _jspx_th_c_005fchoose_005f0 = (org.apache.taglibs.standard.tag.common.core.ChooseTag) _005fjspx_005ftagPool_005fc_005fchoose.get(org.apache.taglibs.standard.tag.common.core.ChooseTag.class);
    boolean _jspx_th_c_005fchoose_005f0_reused = false;
    try {
      _jspx_th_c_005fchoose_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fchoose_005f0.setParent(null);
      int _jspx_eval_c_005fchoose_005f0 = _jspx_th_c_005fchoose_005f0.doStartTag();
      if (_jspx_eval_c_005fchoose_005f0 != jakarta.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("               ");
          if (_jspx_meth_c_005fwhen_005f0(_jspx_th_c_005fchoose_005f0, _jspx_page_context))
            return true;
          out.write("\r\n");
          out.write("               ");
          if (_jspx_meth_c_005fotherwise_005f0(_jspx_th_c_005fchoose_005f0, _jspx_page_context))
            return true;
          out.write("\r\n");
          out.write("            ");
          int evalDoAfterBody = _jspx_th_c_005fchoose_005f0.doAfterBody();
          if (evalDoAfterBody != jakarta.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fchoose_005f0.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fchoose.reuse(_jspx_th_c_005fchoose_005f0);
      _jspx_th_c_005fchoose_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fchoose_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fchoose_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fwhen_005f0(jakarta.servlet.jsp.tagext.JspTag _jspx_th_c_005fchoose_005f0, jakarta.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    jakarta.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:when
    org.apache.taglibs.standard.tag.rt.core.WhenTag _jspx_th_c_005fwhen_005f0 = (org.apache.taglibs.standard.tag.rt.core.WhenTag) _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.WhenTag.class);
    boolean _jspx_th_c_005fwhen_005f0_reused = false;
    try {
      _jspx_th_c_005fwhen_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fwhen_005f0.setParent((jakarta.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f0);
      // /WEB-INF/views/dashboard.jsp(171,15) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fwhen_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${empty allActiveCaisses}", boolean.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fwhen_005f0 = _jspx_th_c_005fwhen_005f0.doStartTag();
      if (_jspx_eval_c_005fwhen_005f0 != jakarta.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("                  <div style=\"text-align: center; padding: 3rem 2rem; color: #6c757d;\">\r\n");
          out.write("                     <div style=\"font-size: 4rem; margin-bottom: 1rem; opacity: 0.5;\">🏦</div>\r\n");
          out.write("                     <h4 style=\"margin-bottom: 0.5rem; color: #495057;\">Aucune caisse active</h4>\r\n");
          out.write("                     <p style=\"margin-bottom: 1.5rem; color: #8d99ae;\">Toutes les caisses sont inactives ou aucune caisse n'existe</p>\r\n");
          out.write("                     <a href=\"/caisses/creer\" style=\"display: inline-block; padding: 0.75rem 1.5rem; background: #4361ee; color: white; text-decoration: none; border-radius: 25px; font-weight: 600; transition: all 0.3s ease;\">Créer une caisse</a>\r\n");
          out.write("                  </div>\r\n");
          out.write("               ");
          int evalDoAfterBody = _jspx_th_c_005fwhen_005f0.doAfterBody();
          if (evalDoAfterBody != jakarta.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fwhen_005f0.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.reuse(_jspx_th_c_005fwhen_005f0);
      _jspx_th_c_005fwhen_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fwhen_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fwhen_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fotherwise_005f0(jakarta.servlet.jsp.tagext.JspTag _jspx_th_c_005fchoose_005f0, jakarta.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    jakarta.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:otherwise
    org.apache.taglibs.standard.tag.common.core.OtherwiseTag _jspx_th_c_005fotherwise_005f0 = (org.apache.taglibs.standard.tag.common.core.OtherwiseTag) _005fjspx_005ftagPool_005fc_005fotherwise.get(org.apache.taglibs.standard.tag.common.core.OtherwiseTag.class);
    boolean _jspx_th_c_005fotherwise_005f0_reused = false;
    try {
      _jspx_th_c_005fotherwise_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fotherwise_005f0.setParent((jakarta.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f0);
      int _jspx_eval_c_005fotherwise_005f0 = _jspx_th_c_005fotherwise_005f0.doStartTag();
      if (_jspx_eval_c_005fotherwise_005f0 != jakarta.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("                  ");
          if (_jspx_meth_c_005fforEach_005f0(_jspx_th_c_005fotherwise_005f0, _jspx_page_context))
            return true;
          out.write("\r\n");
          out.write("               ");
          int evalDoAfterBody = _jspx_th_c_005fotherwise_005f0.doAfterBody();
          if (evalDoAfterBody != jakarta.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fotherwise_005f0.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fotherwise.reuse(_jspx_th_c_005fotherwise_005f0);
      _jspx_th_c_005fotherwise_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fotherwise_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fotherwise_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f0(jakarta.servlet.jsp.tagext.JspTag _jspx_th_c_005fotherwise_005f0, jakarta.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    jakarta.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f0_reused = false;
    try {
      _jspx_th_c_005fforEach_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f0.setParent((jakarta.servlet.jsp.tagext.Tag) _jspx_th_c_005fotherwise_005f0);
      // /WEB-INF/views/dashboard.jsp(180,18) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setVar("caisse");
      // /WEB-INF/views/dashboard.jsp(180,18) name = items type = jakarta.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setItems(new org.apache.jasper.el.JspValueExpression("/WEB-INF/views/dashboard.jsp(180,18) '${allActiveCaisses}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${allActiveCaisses}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int[] _jspx_push_body_count_c_005fforEach_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f0 = _jspx_th_c_005fforEach_005f0.doStartTag();
        if (_jspx_eval_c_005fforEach_005f0 != jakarta.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("                     <div style=\"display: flex; justify-content: space-between; align-items: flex-start; padding: 1rem; margin-bottom: 0.75rem; background: #f8f9fa; border-radius: 10px; border-left: 4px solid #4361ee; transition: background-color 0.2s ease;\">\r\n");
            out.write("                        <div style=\"flex: 1;\">\r\n");
            out.write("                           <strong style=\"color: #4361ee; display: block; font-weight: 600; font-size: 1rem; margin-bottom: 0.25rem;\">");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${caisse.code}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</strong>\r\n");
            out.write("                           <span style=\"color: #495057; font-size: 0.9rem; display: block; margin-bottom: 0.5rem;\">");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${caisse.nom}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</span>\r\n");
            out.write("                           <div style=\"display: flex; gap: 0.5rem; flex-wrap: wrap;\">\r\n");
            out.write("                              <span style=\"background: #e9ecef; color: #495057; padding: 0.3rem 0.6rem; border-radius: 8px; font-size: 0.75rem; font-weight: 600;\">Partition: ");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${caisse.codePartition}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</span>\r\n");
            out.write("                              <span style=\"background: #e9ecef; color: #495057; padding: 0.3rem 0.6rem; border-radius: 8px; font-size: 0.75rem; font-weight: 600;\">CR: ");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${caisse.codeCr}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</span>\r\n");
            out.write("                           </div>\r\n");
            out.write("                        </div>\r\n");
            out.write("                        <span style=\"background: #d4edda; color: #155724; padding: 0.5rem 0.75rem; border-radius: 12px; font-size: 0.8rem; font-weight: 600; border: 1px solid #c3e6cb;\">✅ Active</span>\r\n");
            out.write("                     </div>\r\n");
            out.write("                  ");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f0.doAfterBody();
            if (evalDoAfterBody != jakarta.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f0.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f0.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f0);
      _jspx_th_c_005fforEach_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fchoose_005f1(jakarta.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    jakarta.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:choose
    org.apache.taglibs.standard.tag.common.core.ChooseTag _jspx_th_c_005fchoose_005f1 = (org.apache.taglibs.standard.tag.common.core.ChooseTag) _005fjspx_005ftagPool_005fc_005fchoose.get(org.apache.taglibs.standard.tag.common.core.ChooseTag.class);
    boolean _jspx_th_c_005fchoose_005f1_reused = false;
    try {
      _jspx_th_c_005fchoose_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fchoose_005f1.setParent(null);
      int _jspx_eval_c_005fchoose_005f1 = _jspx_th_c_005fchoose_005f1.doStartTag();
      if (_jspx_eval_c_005fchoose_005f1 != jakarta.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("               ");
          if (_jspx_meth_c_005fwhen_005f1(_jspx_th_c_005fchoose_005f1, _jspx_page_context))
            return true;
          out.write("\r\n");
          out.write("               ");
          if (_jspx_meth_c_005fotherwise_005f1(_jspx_th_c_005fchoose_005f1, _jspx_page_context))
            return true;
          out.write("\r\n");
          out.write("            ");
          int evalDoAfterBody = _jspx_th_c_005fchoose_005f1.doAfterBody();
          if (evalDoAfterBody != jakarta.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fchoose_005f1.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fchoose.reuse(_jspx_th_c_005fchoose_005f1);
      _jspx_th_c_005fchoose_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fchoose_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fchoose_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fwhen_005f1(jakarta.servlet.jsp.tagext.JspTag _jspx_th_c_005fchoose_005f1, jakarta.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    jakarta.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:when
    org.apache.taglibs.standard.tag.rt.core.WhenTag _jspx_th_c_005fwhen_005f1 = (org.apache.taglibs.standard.tag.rt.core.WhenTag) _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.WhenTag.class);
    boolean _jspx_th_c_005fwhen_005f1_reused = false;
    try {
      _jspx_th_c_005fwhen_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fwhen_005f1.setParent((jakarta.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f1);
      // /WEB-INF/views/dashboard.jsp(206,15) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fwhen_005f1.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${empty allActiveTests}", boolean.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fwhen_005f1 = _jspx_th_c_005fwhen_005f1.doStartTag();
      if (_jspx_eval_c_005fwhen_005f1 != jakarta.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("                  <div style=\"text-align: center; padding: 3rem 2rem; color: #6c757d;\">\r\n");
          out.write("                     <div style=\"font-size: 4rem; margin-bottom: 1rem; opacity: 0.5;\">🧪</div>\r\n");
          out.write("                     <h4 style=\"margin-bottom: 0.5rem; color: #495057;\">Aucun test actif</h4>\r\n");
          out.write("                     <p style=\"margin-bottom: 1.5rem; color: #8d99ae;\">Tous les tests sont inactifs ou aucun test n'existe</p>\r\n");
          out.write("                     <a href=\"/tests/creer\" style=\"display: inline-block; padding: 0.75rem 1.5rem; background: #4361ee; color: white; text-decoration: none; border-radius: 25px; font-weight: 600; transition: all 0.3s ease;\">Créer un test</a>\r\n");
          out.write("                  </div>\r\n");
          out.write("               ");
          int evalDoAfterBody = _jspx_th_c_005fwhen_005f1.doAfterBody();
          if (evalDoAfterBody != jakarta.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fwhen_005f1.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.reuse(_jspx_th_c_005fwhen_005f1);
      _jspx_th_c_005fwhen_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fwhen_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fwhen_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fotherwise_005f1(jakarta.servlet.jsp.tagext.JspTag _jspx_th_c_005fchoose_005f1, jakarta.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    jakarta.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:otherwise
    org.apache.taglibs.standard.tag.common.core.OtherwiseTag _jspx_th_c_005fotherwise_005f1 = (org.apache.taglibs.standard.tag.common.core.OtherwiseTag) _005fjspx_005ftagPool_005fc_005fotherwise.get(org.apache.taglibs.standard.tag.common.core.OtherwiseTag.class);
    boolean _jspx_th_c_005fotherwise_005f1_reused = false;
    try {
      _jspx_th_c_005fotherwise_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fotherwise_005f1.setParent((jakarta.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f1);
      int _jspx_eval_c_005fotherwise_005f1 = _jspx_th_c_005fotherwise_005f1.doStartTag();
      if (_jspx_eval_c_005fotherwise_005f1 != jakarta.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("                  ");
          if (_jspx_meth_c_005fforEach_005f1(_jspx_th_c_005fotherwise_005f1, _jspx_page_context))
            return true;
          out.write("\r\n");
          out.write("               ");
          int evalDoAfterBody = _jspx_th_c_005fotherwise_005f1.doAfterBody();
          if (evalDoAfterBody != jakarta.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fotherwise_005f1.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fotherwise.reuse(_jspx_th_c_005fotherwise_005f1);
      _jspx_th_c_005fotherwise_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fotherwise_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fotherwise_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f1(jakarta.servlet.jsp.tagext.JspTag _jspx_th_c_005fotherwise_005f1, jakarta.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    jakarta.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f1 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f1_reused = false;
    try {
      _jspx_th_c_005fforEach_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f1.setParent((jakarta.servlet.jsp.tagext.Tag) _jspx_th_c_005fotherwise_005f1);
      // /WEB-INF/views/dashboard.jsp(215,18) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f1.setVar("test");
      // /WEB-INF/views/dashboard.jsp(215,18) name = items type = jakarta.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f1.setItems(new org.apache.jasper.el.JspValueExpression("/WEB-INF/views/dashboard.jsp(215,18) '${allActiveTests}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${allActiveTests}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int[] _jspx_push_body_count_c_005fforEach_005f1 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f1 = _jspx_th_c_005fforEach_005f1.doStartTag();
        if (_jspx_eval_c_005fforEach_005f1 != jakarta.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("                     <div style=\"display: flex; justify-content: space-between; align-items: flex-start; padding: 1rem; margin-bottom: 0.75rem; background: #f8f9fa; border-radius: 10px; border-left: 4px solid #4361ee; transition: background-color 0.2s ease;\">\r\n");
            out.write("                        <div style=\"flex: 1;\">\r\n");
            out.write("                           <strong style=\"color: #4361ee; display: block; font-weight: 600; font-size: 1rem; margin-bottom: 0.25rem;\">");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${test.codeTest}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</strong>\r\n");
            out.write("                           <span style=\"color: #495057; font-size: 0.9rem; display: block; margin-bottom: 0.5rem;\">");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${test.nomTest}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</span>\r\n");
            out.write("                           <div style=\"display: flex; gap: 0.5rem; flex-wrap: wrap;\">\r\n");
            out.write("                              <span style=\"padding: 0.3rem 0.6rem; border-radius: 8px; font-size: 0.75rem; font-weight: 600; color: white; background: ");
            if (_jspx_meth_c_005fchoose_005f2(_jspx_th_c_005fforEach_005f1, _jspx_page_context, _jspx_push_body_count_c_005fforEach_005f1))
              return true;
            out.write(';');
            out.write('"');
            out.write('>');
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${test.typeTest}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</span>\r\n");
            out.write("                              <span style=\"background: #e9ecef; color: #495057; padding: 0.3rem 0.6rem; border-radius: 8px; font-size: 0.75rem; font-weight: 600;\">");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${test.methodeHttp}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</span>\r\n");
            out.write("                              ");
            if (_jspx_meth_c_005fif_005f0(_jspx_th_c_005fforEach_005f1, _jspx_page_context, _jspx_push_body_count_c_005fforEach_005f1))
              return true;
            out.write("\r\n");
            out.write("                           </div>\r\n");
            out.write("                        </div>\r\n");
            out.write("                        <span style=\"background: #d4edda; color: #155724; padding: 0.5rem 0.75rem; border-radius: 12px; font-size: 0.8rem; font-weight: 600; border: 1px solid #c3e6cb;\">✅ Actif</span>\r\n");
            out.write("                     </div>\r\n");
            out.write("                  ");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f1.doAfterBody();
            if (evalDoAfterBody != jakarta.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f1.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f1[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f1.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f1.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f1);
      _jspx_th_c_005fforEach_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fchoose_005f2(jakarta.servlet.jsp.tagext.JspTag _jspx_th_c_005fforEach_005f1, jakarta.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_c_005fforEach_005f1)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    jakarta.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:choose
    org.apache.taglibs.standard.tag.common.core.ChooseTag _jspx_th_c_005fchoose_005f2 = (org.apache.taglibs.standard.tag.common.core.ChooseTag) _005fjspx_005ftagPool_005fc_005fchoose.get(org.apache.taglibs.standard.tag.common.core.ChooseTag.class);
    boolean _jspx_th_c_005fchoose_005f2_reused = false;
    try {
      _jspx_th_c_005fchoose_005f2.setPageContext(_jspx_page_context);
      _jspx_th_c_005fchoose_005f2.setParent((jakarta.servlet.jsp.tagext.Tag) _jspx_th_c_005fforEach_005f1);
      int _jspx_eval_c_005fchoose_005f2 = _jspx_th_c_005fchoose_005f2.doStartTag();
      if (_jspx_eval_c_005fchoose_005f2 != jakarta.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          if (_jspx_meth_c_005fwhen_005f2(_jspx_th_c_005fchoose_005f2, _jspx_page_context, _jspx_push_body_count_c_005fforEach_005f1))
            return true;
          if (_jspx_meth_c_005fwhen_005f3(_jspx_th_c_005fchoose_005f2, _jspx_page_context, _jspx_push_body_count_c_005fforEach_005f1))
            return true;
          if (_jspx_meth_c_005fwhen_005f4(_jspx_th_c_005fchoose_005f2, _jspx_page_context, _jspx_push_body_count_c_005fforEach_005f1))
            return true;
          if (_jspx_meth_c_005fwhen_005f5(_jspx_th_c_005fchoose_005f2, _jspx_page_context, _jspx_push_body_count_c_005fforEach_005f1))
            return true;
          if (_jspx_meth_c_005fotherwise_005f2(_jspx_th_c_005fchoose_005f2, _jspx_page_context, _jspx_push_body_count_c_005fforEach_005f1))
            return true;
          int evalDoAfterBody = _jspx_th_c_005fchoose_005f2.doAfterBody();
          if (evalDoAfterBody != jakarta.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fchoose_005f2.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fchoose.reuse(_jspx_th_c_005fchoose_005f2);
      _jspx_th_c_005fchoose_005f2_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fchoose_005f2, _jsp_getInstanceManager(), _jspx_th_c_005fchoose_005f2_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fwhen_005f2(jakarta.servlet.jsp.tagext.JspTag _jspx_th_c_005fchoose_005f2, jakarta.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_c_005fforEach_005f1)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    jakarta.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:when
    org.apache.taglibs.standard.tag.rt.core.WhenTag _jspx_th_c_005fwhen_005f2 = (org.apache.taglibs.standard.tag.rt.core.WhenTag) _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.WhenTag.class);
    boolean _jspx_th_c_005fwhen_005f2_reused = false;
    try {
      _jspx_th_c_005fwhen_005f2.setPageContext(_jspx_page_context);
      _jspx_th_c_005fwhen_005f2.setParent((jakarta.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f2);
      // /WEB-INF/views/dashboard.jsp(221,161) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fwhen_005f2.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${test.typeTest == 'HTTP'}", boolean.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fwhen_005f2 = _jspx_th_c_005fwhen_005f2.doStartTag();
      if (_jspx_eval_c_005fwhen_005f2 != jakarta.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("#3498db");
          int evalDoAfterBody = _jspx_th_c_005fwhen_005f2.doAfterBody();
          if (evalDoAfterBody != jakarta.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fwhen_005f2.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.reuse(_jspx_th_c_005fwhen_005f2);
      _jspx_th_c_005fwhen_005f2_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fwhen_005f2, _jsp_getInstanceManager(), _jspx_th_c_005fwhen_005f2_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fwhen_005f3(jakarta.servlet.jsp.tagext.JspTag _jspx_th_c_005fchoose_005f2, jakarta.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_c_005fforEach_005f1)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    jakarta.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:when
    org.apache.taglibs.standard.tag.rt.core.WhenTag _jspx_th_c_005fwhen_005f3 = (org.apache.taglibs.standard.tag.rt.core.WhenTag) _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.WhenTag.class);
    boolean _jspx_th_c_005fwhen_005f3_reused = false;
    try {
      _jspx_th_c_005fwhen_005f3.setPageContext(_jspx_page_context);
      _jspx_th_c_005fwhen_005f3.setParent((jakarta.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f2);
      // /WEB-INF/views/dashboard.jsp(221,219) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fwhen_005f3.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${test.typeTest == 'HTTPS'}", boolean.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fwhen_005f3 = _jspx_th_c_005fwhen_005f3.doStartTag();
      if (_jspx_eval_c_005fwhen_005f3 != jakarta.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("#2ecc71");
          int evalDoAfterBody = _jspx_th_c_005fwhen_005f3.doAfterBody();
          if (evalDoAfterBody != jakarta.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fwhen_005f3.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.reuse(_jspx_th_c_005fwhen_005f3);
      _jspx_th_c_005fwhen_005f3_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fwhen_005f3, _jsp_getInstanceManager(), _jspx_th_c_005fwhen_005f3_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fwhen_005f4(jakarta.servlet.jsp.tagext.JspTag _jspx_th_c_005fchoose_005f2, jakarta.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_c_005fforEach_005f1)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    jakarta.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:when
    org.apache.taglibs.standard.tag.rt.core.WhenTag _jspx_th_c_005fwhen_005f4 = (org.apache.taglibs.standard.tag.rt.core.WhenTag) _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.WhenTag.class);
    boolean _jspx_th_c_005fwhen_005f4_reused = false;
    try {
      _jspx_th_c_005fwhen_005f4.setPageContext(_jspx_page_context);
      _jspx_th_c_005fwhen_005f4.setParent((jakarta.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f2);
      // /WEB-INF/views/dashboard.jsp(221,278) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fwhen_005f4.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${test.typeTest == 'TCP'}", boolean.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fwhen_005f4 = _jspx_th_c_005fwhen_005f4.doStartTag();
      if (_jspx_eval_c_005fwhen_005f4 != jakarta.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("#e74c3c");
          int evalDoAfterBody = _jspx_th_c_005fwhen_005f4.doAfterBody();
          if (evalDoAfterBody != jakarta.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fwhen_005f4.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.reuse(_jspx_th_c_005fwhen_005f4);
      _jspx_th_c_005fwhen_005f4_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fwhen_005f4, _jsp_getInstanceManager(), _jspx_th_c_005fwhen_005f4_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fwhen_005f5(jakarta.servlet.jsp.tagext.JspTag _jspx_th_c_005fchoose_005f2, jakarta.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_c_005fforEach_005f1)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    jakarta.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:when
    org.apache.taglibs.standard.tag.rt.core.WhenTag _jspx_th_c_005fwhen_005f5 = (org.apache.taglibs.standard.tag.rt.core.WhenTag) _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.WhenTag.class);
    boolean _jspx_th_c_005fwhen_005f5_reused = false;
    try {
      _jspx_th_c_005fwhen_005f5.setPageContext(_jspx_page_context);
      _jspx_th_c_005fwhen_005f5.setParent((jakarta.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f2);
      // /WEB-INF/views/dashboard.jsp(221,335) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fwhen_005f5.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${test.typeTest == 'PING'}", boolean.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fwhen_005f5 = _jspx_th_c_005fwhen_005f5.doStartTag();
      if (_jspx_eval_c_005fwhen_005f5 != jakarta.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("#f39c12");
          int evalDoAfterBody = _jspx_th_c_005fwhen_005f5.doAfterBody();
          if (evalDoAfterBody != jakarta.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fwhen_005f5.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.reuse(_jspx_th_c_005fwhen_005f5);
      _jspx_th_c_005fwhen_005f5_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fwhen_005f5, _jsp_getInstanceManager(), _jspx_th_c_005fwhen_005f5_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fotherwise_005f2(jakarta.servlet.jsp.tagext.JspTag _jspx_th_c_005fchoose_005f2, jakarta.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_c_005fforEach_005f1)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    jakarta.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:otherwise
    org.apache.taglibs.standard.tag.common.core.OtherwiseTag _jspx_th_c_005fotherwise_005f2 = (org.apache.taglibs.standard.tag.common.core.OtherwiseTag) _005fjspx_005ftagPool_005fc_005fotherwise.get(org.apache.taglibs.standard.tag.common.core.OtherwiseTag.class);
    boolean _jspx_th_c_005fotherwise_005f2_reused = false;
    try {
      _jspx_th_c_005fotherwise_005f2.setPageContext(_jspx_page_context);
      _jspx_th_c_005fotherwise_005f2.setParent((jakarta.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f2);
      int _jspx_eval_c_005fotherwise_005f2 = _jspx_th_c_005fotherwise_005f2.doStartTag();
      if (_jspx_eval_c_005fotherwise_005f2 != jakarta.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("#9b59b6");
          int evalDoAfterBody = _jspx_th_c_005fotherwise_005f2.doAfterBody();
          if (evalDoAfterBody != jakarta.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fotherwise_005f2.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fotherwise.reuse(_jspx_th_c_005fotherwise_005f2);
      _jspx_th_c_005fotherwise_005f2_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fotherwise_005f2, _jsp_getInstanceManager(), _jspx_th_c_005fotherwise_005f2_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f0(jakarta.servlet.jsp.tagext.JspTag _jspx_th_c_005fforEach_005f1, jakarta.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_c_005fforEach_005f1)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    jakarta.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f0_reused = false;
    try {
      _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f0.setParent((jakarta.servlet.jsp.tagext.Tag) _jspx_th_c_005fforEach_005f1);
      // /WEB-INF/views/dashboard.jsp(223,30) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${not empty test.endpoint}", boolean.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
      if (_jspx_eval_c_005fif_005f0 != jakarta.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("                                 <span style=\"background: #e9ecef; color: #495057; padding: 0.3rem 0.6rem; border-radius: 8px; font-size: 0.75rem; font-weight: 600; max-width: 150px; overflow: hidden; text-overflow: ellipsis; white-space: nowrap;\">");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${test.endpoint}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("</span>\r\n");
          out.write("                              ");
          int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
          if (evalDoAfterBody != jakarta.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f0.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
      _jspx_th_c_005fif_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f0_reused);
    }
    return false;
  }
}
