/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.16
 * Generated at: 2025-11-20 21:54:00 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.rapports;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class list_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(4);
    _jspx_dependants.put("jar:file:/C:/Users/el_ch/.m2/repository/org/glassfish/web/jakarta.servlet.jsp.jstl/3.0.1/jakarta.servlet.jsp.jstl-3.0.1.jar!/META-INF/c-1_2.tld", Long.valueOf(1664446278000L));
    _jspx_dependants.put("file:/C:/Users/el_ch/.m2/repository/org/glassfish/web/jakarta.servlet.jsp.jstl/3.0.1/jakarta.servlet.jsp.jstl-3.0.1.jar", Long.valueOf(1762018565336L));
    _jspx_dependants.put("/WEB-INF/views/rapports/../includes/header.jsp", Long.valueOf(1763675179948L));
    _jspx_dependants.put("/WEB-INF/views/rapports/../includes/footer.jsp", Long.valueOf(1763675376776L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"fr\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <title>Machine Monitor</title>\r\n");
      out.write("    <style>\r\n");
      out.write("        :root {\r\n");
      out.write("            --primary: #4361ee;\r\n");
      out.write("            --secondary: #3a0ca3;\r\n");
      out.write("            --gradient: linear-gradient(135deg, #4361ee, #3a0ca3);\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        * {\r\n");
      out.write("            margin: 0;\r\n");
      out.write("            padding: 0;\r\n");
      out.write("            box-sizing: border-box;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        body {\r\n");
      out.write("            font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;\r\n");
      out.write("            background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);\r\n");
      out.write("            min-height: 100vh;\r\n");
      out.write("            color: #2b2d42;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        /* Navigation SIMPLIFIÉE */\r\n");
      out.write("        .navbar {\r\n");
      out.write("            background: rgba(255, 255, 255, 0.98);\r\n");
      out.write("            padding: 1rem 2rem;\r\n");
      out.write("            display: flex;\r\n");
      out.write("            justify-content: space-between;\r\n");
      out.write("            align-items: center;\r\n");
      out.write("            box-shadow: 0 4px 6px -1px rgba(0, 0, 0, 0.1);\r\n");
      out.write("            border-bottom: 3px solid var(--primary);\r\n");
      out.write("            flex-wrap: wrap;\r\n");
      out.write("            gap: 1rem;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .nav-brand h1 {\r\n");
      out.write("            background: var(--gradient);\r\n");
      out.write("            -webkit-background-clip: text;\r\n");
      out.write("            -webkit-text-fill-color: transparent;\r\n");
      out.write("            background-clip: text;\r\n");
      out.write("            font-size: 1.8rem;\r\n");
      out.write("            font-weight: 700;\r\n");
      out.write("            white-space: nowrap;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .nav-links {\r\n");
      out.write("            display: flex;\r\n");
      out.write("            gap: 1rem;\r\n");
      out.write("            align-items: center;\r\n");
      out.write("            flex-wrap: wrap;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .nav-link {\r\n");
      out.write("            color: #2b2d42;\r\n");
      out.write("            text-decoration: none;\r\n");
      out.write("            padding: 0.6rem 1.2rem;\r\n");
      out.write("            border-radius: 25px;\r\n");
      out.write("            font-weight: 600;\r\n");
      out.write("            transition: all 0.3s ease;\r\n");
      out.write("            background: rgba(67, 97, 238, 0.1);\r\n");
      out.write("            white-space: nowrap;\r\n");
      out.write("            font-size: 0.9rem;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .nav-link:hover,\r\n");
      out.write("        .nav-link.active {\r\n");
      out.write("            background: var(--gradient);\r\n");
      out.write("            color: white;\r\n");
      out.write("            transform: translateY(-2px);\r\n");
      out.write("            box-shadow: 0 4px 15px rgba(67, 97, 238, 0.3);\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        /* Indicateur de status */\r\n");
      out.write("        .status-indicator {\r\n");
      out.write("            display: inline-flex;\r\n");
      out.write("            align-items: center;\r\n");
      out.write("            gap: 0.5rem;\r\n");
      out.write("            padding: 0.4rem 0.8rem;\r\n");
      out.write("            border-radius: 20px;\r\n");
      out.write("            font-size: 0.75rem;\r\n");
      out.write("            font-weight: 600;\r\n");
      out.write("            background: rgba(67, 97, 238, 0.1);\r\n");
      out.write("            color: var(--primary);\r\n");
      out.write("            white-space: nowrap;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .status-dot {\r\n");
      out.write("            width: 8px;\r\n");
      out.write("            height: 8px;\r\n");
      out.write("            border-radius: 50%;\r\n");
      out.write("            background: #06d6a0;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .status-down .status-dot {\r\n");
      out.write("            background: #ef476f;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        /* Responsive */\r\n");
      out.write("        @media (max-width: 768px) {\r\n");
      out.write("            .navbar {\r\n");
      out.write("                flex-direction: column;\r\n");
      out.write("                padding: 1rem;\r\n");
      out.write("                gap: 1rem;\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            .nav-links {\r\n");
      out.write("                justify-content: center;\r\n");
      out.write("                gap: 0.5rem;\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            .nav-link {\r\n");
      out.write("                padding: 0.5rem 1rem;\r\n");
      out.write("                font-size: 0.8rem;\r\n");
      out.write("            }\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .container {\r\n");
      out.write("            max-width: 1400px;\r\n");
      out.write("            margin: 2rem auto;\r\n");
      out.write("            padding: 0 2rem;\r\n");
      out.write("        }\r\n");
      out.write("    </style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("    <nav class=\"navbar\">\r\n");
      out.write("        <div class=\"nav-brand\">\r\n");
      out.write("            <h1>🚀 Machine Monitor</h1>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"nav-links\">\r\n");
      out.write("            <a href=\"/dashboard\" class=\"nav-link\">📊 Dashboard</a>\r\n");
      out.write("            <a href=\"/caisses\" class=\"nav-link\">🏦 Caisses</a>\r\n");
      out.write("            <a href=\"/tests\" class=\"nav-link\">🧪 Tests</a>\r\n");
      out.write("            <a href=\"/rapports\" class=\"nav-link\">📈 Rapports</a>\r\n");
      out.write("            <a href=\"/monitoring/metrics-dashboard\" class=\"nav-link\">📊 Monitoring</a>\r\n");
      out.write("\r\n");
      out.write("            <div class=\"status-indicator\" id=\"statusIndicator\">\r\n");
      out.write("                <div class=\"status-dot\"></div>\r\n");
      out.write("                <span id=\"statusText\">System OK</span>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </nav>\r\n");
      out.write("\r\n");
      out.write("    <main class=\"container\">");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div class=\"dashboard\">\r\n");
      out.write("    <div class=\"page-header\">\r\n");
      out.write("        <h2>📈 Rapports de Supervision</h2>\r\n");
      out.write("        <a href=\"/dashboard\" class=\"btn btn-primary\">← Retour au Dashboard</a>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <!-- Indicateur de statut -->\r\n");
      out.write("    <div style=\"background: linear-gradient(135deg, #4cc9f0, #4361ee); color: white; padding: 1rem; border-radius: 10px; margin-bottom: 1rem;\">\r\n");
      out.write("        <div style=\"display: flex; justify-content: space-between; align-items: center;\">\r\n");
      out.write("            <div>\r\n");
      out.write("                <strong>📊 Rapports Hebdomadaires</strong>\r\n");
      out.write("                <div style=\"font-size: 0.9rem; opacity: 0.9;\">\r\n");
      out.write("                    Période du ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${rapports.periode}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div style=\"font-size: 0.8rem; background: rgba(255,255,255,0.2); padding: 0.25rem 0.75rem; border-radius: 15px;\">\r\n");
      out.write("                📅 Données statistiques\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <!-- Cartes de statistiques -->\r\n");
      out.write("    <div style=\"display: grid; grid-template-columns: repeat(auto-fit, minmax(250px, 1fr)); gap: 1.5rem; margin-bottom: 2rem;\">\r\n");
      out.write("        <div style=\"background: white; padding: 2rem; border-radius: 15px; text-align: center; box-shadow: 0 4px 6px rgba(0,0,0,0.1);\">\r\n");
      out.write("            <div style=\"font-size: 2.5rem; margin-bottom: 0.5rem;\">📊</div>\r\n");
      out.write("            <div style=\"font-size: 3rem; font-weight: bold; color: #4361ee; margin-bottom: 0.5rem;\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${rapports.totalTests}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</div>\r\n");
      out.write("            <div style=\"font-size: 1.2rem; font-weight: 600; color: #495057; margin-bottom: 0.25rem;\">Tests Exécutés</div>\r\n");
      out.write("            <div style=\"font-size: 0.9rem; color: #6c757d;\">Cette semaine</div>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <div style=\"background: white; padding: 2rem; border-radius: 15px; text-align: center; box-shadow: 0 4px 6px rgba(0,0,0,0.1);\">\r\n");
      out.write("            <div style=\"font-size: 2.5rem; margin-bottom: 0.5rem;\">✅</div>\r\n");
      out.write("            <div style=\"font-size: 3rem; font-weight: bold; color: #28a745; margin-bottom: 0.5rem;\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${rapports.testsReussis}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</div>\r\n");
      out.write("            <div style=\"font-size: 1.2rem; font-weight: 600; color: #495057; margin-bottom: 0.25rem;\">Tests Réussis</div>\r\n");
      out.write("            <div style=\"font-size: 0.9rem; color: #6c757d;\">Cette semaine</div>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <div style=\"background: white; padding: 2rem; border-radius: 15px; text-align: center; box-shadow: 0 4px 6px rgba(0,0,0,0.1);\">\r\n");
      out.write("            <div style=\"font-size: 2.5rem; margin-bottom: 0.5rem;\">📈</div>\r\n");
      out.write("            <div style=\"font-size: 3rem; font-weight: bold; color: #ffc107; margin-bottom: 0.5rem;\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${rapports.tauxReussite}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("%</div>\r\n");
      out.write("            <div style=\"font-size: 1.2rem; font-weight: 600; color: #495057; margin-bottom: 0.25rem;\">Taux de Réussite</div>\r\n");
      out.write("            <div style=\"font-size: 0.9rem; color: #6c757d;\">Moyenne hebdo</div>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <div style=\"background: white; padding: 2rem; border-radius: 15px; text-align: center; box-shadow: 0 4px 6px rgba(0,0,0,0.1);\">\r\n");
      out.write("            <div style=\"font-size: 2.5rem; margin-bottom: 0.5rem;\">⚡</div>\r\n");
      out.write("            <div style=\"font-size: 3rem; font-weight: bold; color: #17a2b8; margin-bottom: 0.5rem;\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${rapports.tempsReponseMoyen}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("ms</div>\r\n");
      out.write("            <div style=\"font-size: 1.2rem; font-weight: 600; color: #495057; margin-bottom: 0.25rem;\">Temps Réponse</div>\r\n");
      out.write("            <div style=\"font-size: 0.9rem; color: #6c757d;\">Moyen</div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <!-- Informations supplémentaires -->\r\n");
      out.write("    <div style=\"background: white; border-radius: 15px; box-shadow: 0 4px 6px rgba(0,0,0,0.1); overflow: hidden; margin-bottom: 2rem;\">\r\n");
      out.write("        <div style=\"display: flex; justify-content: space-between; align-items: center; padding: 1.5rem; background: #f8f9fa; border-bottom: 1px solid #e9ecef;\">\r\n");
      out.write("            <h3 style=\"margin: 0; color: #4361ee; font-size: 1.3rem;\">🏦 Informations Système</h3>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div style=\"padding: 1.5rem;\">\r\n");
      out.write("            <div style=\"display: grid; grid-template-columns: 1fr 1fr; gap: 1rem;\">\r\n");
      out.write("                <div>\r\n");
      out.write("                    <h4 style=\"color: #495057; margin-bottom: 0.5rem;\">Caisses Testées</h4>\r\n");
      out.write("                    <div style=\"font-size: 1.5rem; color: #4361ee; font-weight: bold;\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${rapports.caissesTestees}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div>\r\n");
      out.write("                    <h4 style=\"color: #495057; margin-bottom: 0.5rem;\">Tests Actifs</h4>\r\n");
      out.write("                    <div style=\"font-size: 1.5rem; color: #4361ee; font-weight: bold;\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${rapports.testsActifs}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <!-- Actions -->\r\n");
      out.write("    <div style=\"background: white; border-radius: 15px; box-shadow: 0 4px 6px rgba(0,0,0,0.1); overflow: hidden;\">\r\n");
      out.write("        <div style=\"display: flex; justify-content: space-between; align-items: center; padding: 1.5rem; background: #f8f9fa; border-bottom: 1px solid #e9ecef;\">\r\n");
      out.write("            <h3 style=\"margin: 0; color: #4361ee; font-size: 1.3rem;\">🚀 Actions</h3>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div style=\"padding: 1.5rem;\">\r\n");
      out.write("            <div style=\"display: flex; gap: 1rem; flex-wrap: wrap;\">\r\n");
      out.write("                <button onclick=\"window.print()\"\r\n");
      out.write("                        style=\"display: flex; align-items: center; gap: 0.5rem; padding: 0.75rem 1.5rem; background: linear-gradient(135deg, #ff9e00, #ff6b6b); color: white; border: none; border-radius: 12px; font-weight: 600; cursor: pointer; transition: all 0.3s ease;\"\r\n");
      out.write("                        onmouseover=\"this.style.transform='translateY(-2px)'; this.style.boxShadow='0 8px 25px rgba(0,0,0,0.2)';\"\r\n");
      out.write("                        onmouseout=\"this.style.transform='translateY(0)'; this.style.boxShadow='none';\">\r\n");
      out.write("                    <span>🖨️</span>\r\n");
      out.write("                    <span>Imprimer le Rapport</span>\r\n");
      out.write("                </button>\r\n");
      out.write("\r\n");
      out.write("                <a href=\"/dashboard\"\r\n");
      out.write("                   style=\"display: flex; align-items: center; gap: 0.5rem; padding: 0.75rem 1.5rem; background: linear-gradient(135deg, #4361ee, #3a0ca3); color: white; text-decoration: none; border-radius: 12px; font-weight: 600; transition: all 0.3s ease;\"\r\n");
      out.write("                   onmouseover=\"this.style.transform='translateY(-2px)'; this.style.boxShadow='0 8px 25px rgba(0,0,0,0.2)';\"\r\n");
      out.write("                   onmouseout=\"this.style.transform='translateY(0)'; this.style.boxShadow='none';\">\r\n");
      out.write("                    <span>🏠</span>\r\n");
      out.write("                    <span>Retour au Dashboard</span>\r\n");
      out.write("                </a>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write(".dashboard {\r\n");
      out.write("   max-width: 1400px;\r\n");
      out.write("   margin: 0 auto;\r\n");
      out.write("   padding: 20px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".page-header {\r\n");
      out.write("   display: flex;\r\n");
      out.write("   justify-content: space-between;\r\n");
      out.write("   align-items: center;\r\n");
      out.write("   margin-bottom: 2rem;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".btn {\r\n");
      out.write("    display: inline-flex;\r\n");
      out.write("    align-items: center;\r\n");
      out.write("    gap: 0.5rem;\r\n");
      out.write("    padding: 0.75rem 1.5rem;\r\n");
      out.write("    background: #4361ee;\r\n");
      out.write("    color: white;\r\n");
      out.write("    text-decoration: none;\r\n");
      out.write("    border-radius: 25px;\r\n");
      out.write("    font-weight: 600;\r\n");
      out.write("    transition: all 0.3s ease;\r\n");
      out.write("    border: none;\r\n");
      out.write("    cursor: pointer;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".btn:hover {\r\n");
      out.write("    background: #3a0ca3;\r\n");
      out.write("    transform: translateY(-2px);\r\n");
      out.write("    box-shadow: 0 4px 12px rgba(0,0,0,0.2);\r\n");
      out.write("    color: white;\r\n");
      out.write("    text-decoration: none;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".btn-primary {\r\n");
      out.write("    background: #4361ee;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* Responsive */\r\n");
      out.write("@media (max-width: 768px) {\r\n");
      out.write("    .page-header {\r\n");
      out.write("        flex-direction: column;\r\n");
      out.write("        gap: 1rem;\r\n");
      out.write("        text-align: center;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    div[style*=\"grid-template-columns: repeat(auto-fit, minmax(250px, 1fr))\"] {\r\n");
      out.write("        grid-template-columns: 1fr;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    div[style*=\"grid-template-columns: 1fr 1fr\"] {\r\n");
      out.write("        grid-template-columns: 1fr;\r\n");
      out.write("    }\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("</main>\r\n");
      out.write("<footer style=\"\r\n");
      out.write("    background: linear-gradient(135deg, #2c3e50 0%, #34495e 100%);\r\n");
      out.write("    color: white;\r\n");
      out.write("    padding: 1rem 2rem;\r\n");
      out.write("    margin-top: 3rem;\r\n");
      out.write("    border-top: 3px solid #4361ee;\r\n");
      out.write("    font-family: 'Segoe UI', Arial, sans-serif;\r\n");
      out.write("\">\r\n");
      out.write("    <div style=\"max-width: 1400px; margin: 0 auto;\">\r\n");
      out.write("        <!-- Ligne principale -->\r\n");
      out.write("        <div style=\"display: flex; justify-content: space-between; align-items: center; flex-wrap: wrap; gap: 1rem;\">\r\n");
      out.write("            <!-- Section gauche -->\r\n");
      out.write("            <div style=\"text-align: left; flex: 1;\">\r\n");
      out.write("                <h3 style=\"color: #fff; margin: 0; font-size: 1.2rem; font-weight: 600;\">\r\n");
      out.write("                    Machine Monitor\r\n");
      out.write("                </h3>\r\n");
      out.write("                <p style=\"color: #bdc3c7; margin: 0.3rem 0 0 0; font-size: 0.9rem;\">\r\n");
      out.write("                    SystÃ¨me de surveillance des caisses et tests automatisÃ©s\r\n");
      out.write("                </p>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <!-- Section centrale -->\r\n");
      out.write("            <div style=\"text-align: center; flex: 1;\">\r\n");
      out.write("                <p style=\"color: #ecf0f1; margin: 0; font-size: 0.85rem; font-weight: 500;\">\r\n");
      out.write("                    Â© 2024 Machine Monitor - Tous droits rÃ©servÃ©s â¢ DÃ©veloppÃ© avec soin\r\n");
      out.write("                </p>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <!-- Section droite -->\r\n");
      out.write("            <div style=\"text-align: right; flex: 1;\">\r\n");
      out.write("                <div style=\"display: flex; gap: 1.5rem; justify-content: flex-end; margin-bottom: 0.5rem;\">\r\n");
      out.write("                    <span style=\"color: #ecf0f1; font-size: 0.9rem;\">ð Monitoring temps rÃ©el</span>\r\n");
      out.write("                    <span style=\"color: #ecf0f1; font-size: 0.9rem;\">â¡ Performances</span>\r\n");
      out.write("                    <span style=\"color: #ecf0f1; font-size: 0.9rem;\">ð SÃ©curitÃ©</span>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <!-- Ligne secondaire -->\r\n");
      out.write("        <div style=\"margin-top: 1rem; padding-top: 0.8rem; border-top: 1px solid #4a6572;\">\r\n");
      out.write("            <div style=\"display: flex; justify-content: space-between; align-items: center; flex-wrap: wrap; gap: 1rem;\">\r\n");
      out.write("                <div style=\"color: #95a5a6; font-size: 0.8rem;\">\r\n");
      out.write("                    ð¢ Gestion des partitions et CR â¢ ð§ª Tests de conformitÃ©\r\n");
      out.write("                </div>\r\n");
      out.write("                <div style=\"color: #95a5a6; font-size: 0.8rem;\">\r\n");
      out.write("                    ð Dashboard â¢ ð¦ Caisses â¢ ð§ª Tests â¢ ð Monitoring\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</footer>\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("    // VÃ©rification du status\r\n");
      out.write("    function checkHealthStatus() {\r\n");
      out.write("        fetch('/monitoring/health')\r\n");
      out.write("            .then(response => response.json())\r\n");
      out.write("            .then(data => {\r\n");
      out.write("                const statusIndicator = document.getElementById('statusIndicator');\r\n");
      out.write("                const statusText = document.getElementById('statusText');\r\n");
      out.write("\r\n");
      out.write("                if (data.status === 'UP') {\r\n");
      out.write("                    statusIndicator.classList.remove('status-down');\r\n");
      out.write("                    statusText.textContent = 'SystÃ¨me OK';\r\n");
      out.write("                } else {\r\n");
      out.write("                    statusIndicator.classList.add('status-down');\r\n");
      out.write("                    statusText.textContent = 'ProblÃ¨mes';\r\n");
      out.write("                }\r\n");
      out.write("            })\r\n");
      out.write("            .catch(error => {\r\n");
      out.write("                const statusIndicator = document.getElementById('statusIndicator');\r\n");
      out.write("                const statusText = document.getElementById('statusText');\r\n");
      out.write("                statusIndicator.classList.add('status-down');\r\n");
      out.write("                statusText.textContent = 'Erreur';\r\n");
      out.write("            });\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    document.addEventListener('DOMContentLoaded', function() {\r\n");
      out.write("        checkHealthStatus();\r\n");
      out.write("        setInterval(checkHealthStatus, 30000);\r\n");
      out.write("    });\r\n");
      out.write("</script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
